image: node:11.1.0

stages:
  - install
  - test
  # - build
  - deploy

variables:
  MONGODB_URI: "mongodb+srv://antonis162010:1adqZtaQqCo2He6i@cluster0-e8afc.mongodb.net/training-dev?retryWrites=true&w=majority"
  JWT_KEY: 123456
  APP_PORT: 3000
  APP_HOST: localhost
  APP_URL: /api/v1

install-dependencies:
  stage: install
  variables:
    NODE_ENV: test
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'
      when: always
  script:
    - npm install
  artifacts:
    expire_in: 1hr
    paths:
      - node_modules/
  cache:
    paths:
      - node_modules/

test-app:
  stage: test
  variables:
    NODE_ENV: test
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'
      when: always
  dependencies:
    - install-dependencies
  script:
    - npm test

deploy-app:
  image: ubuntu:latest
  stage: deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'
      when: always
  before_script:
    # Check for ssh-agent + rsync and install if not present
    - "which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y  )"
    # Inject the remote's private key
    # - ssh-add <(echo "$SSH_PRIVATE_KEY" | base64 -d)
    # - mkdir -p ~/.ssh
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 700 ~/.ssh
    - eval $(ssh-agent -s)
    - chmod 400 ~/.ssh/id_rsa
    - ssh-add ~/.ssh/id_rsa
    # - ssh-keyscan -H 'gitlab.com' >> ~/.ssh/known_hosts
    # - echo "$SSH_PRIVATE_KEY" | ssh-add -
    # - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  script:
    - ssh root@68.183.115.52 "cd /var/www/html/backmean && git checkout develop && git pull"
