image: docker:19.03.1
services:
  - docker:19.03.1-dind

stages:
  - test
  # - install
  - build
  - deploy

test-app:
  image: mhart/alpine-node:12
  stage: test
  variables:
    NODE_ENV: test
    MONGODB_URI: $DATABASE
    JWT_KEY: 123456
    APP_PORT: 3000
    APP_HOST: localhost
    APP_URL: /api/v1
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'
      when: on_success
  script:
    - apk update
    - yarn
    - yarn test
  allow_failure: false

build-app:
  stage: build
  before_script:
    - apk add gettext
    - envsubst '\$DATABASE' < ./scripts/deploy.sh > ./scripts/deploy.sh
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  script:
    - docker build --tag $DOCKER_USERNAME/backmean:$CI_COMMIT_SHA -f ./Dockerfile ./
    - docker push $DOCKER_USERNAME/backmean:$CI_COMMIT_SHA
  only:
    - develop

deploy-app:
  image: google/cloud-sdk
  stage: deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'
      when: manual
  before_script:
    - apt-get install -y gettext
    - echo $GCLOUD_SERVICE_KEY | base64 -d > ${HOME}/service-account.json
    - gcloud auth activate-service-account --key-file ${HOME}/service-account.json  || die "unable to authenticate service account for gcloud"
    - gcloud container clusters get-credentials $GCLOUD_CLUSTER
    - envsubst < ./system/template-config.yml > ./system/template-replace.yml
  script:
    - kubectl apply -f ./system/template-replace.yml
    - kubectl set image deployments/${FERRETERIA_UID}-deployment --namespace ${NAMESPACE} ${FERRETERIA_UID}-app=$DOCKER_USERNAME/backmean:$CI_COMMIT_SHA
  variables:
    FERRETERIA: 'mi-ferreteria'
    FERRETERIA_UID: '$CI_COMMIT_REF_NAME'
    NAMESPACE: 'development'
