image: node:11.1.0

stages:
  - install
  - test
  # - build
  - deploy

variables:
  MONGODB_URI: "mongodb+srv://antonis162010:1adqZtaQqCo2He6i@cluster0-e8afc.mongodb.net/training-dev?retryWrites=true&w=majority"
  JWT_KEY: 123456
  APP_PORT: 3000
  APP_HOST: localhost
  APP_URL: /api/v1

install-dependencies:
  stage: install
  variables:
    NODE_ENV: test
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'
      when: always
  script:
    - npm install
  artifacts:
    expire_in: 1hr
    paths:
      - node_modules/
  cache:
    paths:
      - node_modules/

test-app:
  stage: test
  variables:
    NODE_ENV: test
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'
      when: always
  dependencies:
    - install-dependencies
  script:
    - npm test

deploy-app:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'
      when: always
  before_script:
    # Check for ssh-agent + rsync and install if not present
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y  )'
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    # Inject the remote's private key
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - chmod 700 ~/.ssh
  script: 
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - ssh root@68.183.115.52 "cd /var/www/html/backmean && git checkout develop && git pull"