image: node:12

stages:
  - install
  - test
  # - build
  - deploy

variables:
  MONGODB_URI: "mongodb+srv://antonis162010:1adqZtaQqCo2He6i@cluster0-e8afc.mongodb.net/training-dev?retryWrites=true&w=majority"
  JWT_KEY: 123456
  APP_PORT: 3000
  APP_HOST: localhost
  APP_URL: /api/v1

install-dependencies:
  stage: install
  variables:
    NODE_ENV: test
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'
      when: always
  script:
    - npm install
  artifacts:
    expire_in: 1hr
    paths:
      - node_modules/
  cache:
    paths:
      - node_modules/

test-app:
  stage: test
  variables:
    NODE_ENV: test
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'
      when: always
  dependencies:
    - install-dependencies
  script:
    - npm test

deploy-app:
  image: ubuntu:latest
  stage: deploy
  allow_failure: false
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'
      when: always
  before_script:
    # Check for ssh-agent + rsync and install if not present
    - "which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y  )"
    - eval $(ssh-agent -s)
    # Inject the remote's private key
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - chmod 700 ~/.ssh
    # # Append keyscan output into known hosts
    - ssh-keyscan 167.71.55.161 >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    # Connect and update branch with new changes
    - ssh root@167.71.55.161 "cd /var/www/backmean && git checkout develop && git pull origin develop"
    # Clean containers and images pass
    # Docker update images and run
    - ssh root@167.71.55.161 "cd /var/www/backmean && docker-compose build && docker-compose up -d"
