image: node:11.1.0

stages:
  - install
  - test

variables:
  NODE_ENV: test
  MONGODB_URI: "mongodb+srv://antonis162010:1adqZtaQqCo2He6i@cluster0-e8afc.mongodb.net/training-dev?retryWrites=true&w=majority"
  JWT_KEY: 123456
  APP_PORT: 3000
  APP_HOST: localhost
  APP_URL: /api/v1

install-dependencies:
  stage: install
  script:
    - npm install
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'
      when: always
  artifacts:
    expire_in: 1hr
    paths:
      - node_modules/
  cache:
    paths:
      - node_modules/

test-app:
  stage: test
  dependencies:
    - install-dependencies
  script:
    - npm test
