language: node_js

cache:
  directories:
    - node_modules
    - ~/.npm

node_js:
  - '12'

git:
  depth: 3

env:
  - NODE_ENV=production
  - MONGODB_URI=mongodb+srv://antonis162010:1adqZtaQqCo2He6i@cluster0-e8afc.mongodb.net/training-dev?retryWrites=true&w=majority

script:
  - yarn test

branches:
  only:
    - master
    - develop

notifications:
  email:
    recipients:
      - antonis162010@gmail.com
    on_success: always
    on_failure: always



