language: node_js

cache:
  directories:
    - node_modules
    - ~/.npm

node_js:
  - '12'

git:
  depth: 3

env:
  - NODE_ENV=production

script:
  - yarn test

branches:
  only:
    - master
    - develop

notifications:
  email:
    recipients:
      - antonis162010@gmail.com
    on_success: always
    on_failure: always



