language: node_js
os: linux

cache:
  directories:
    - node_modules
    - ~/.npm

node_js:
  - '12'

git:
  depth: 3

branches:
  only:
    - master
    - develop

script:
  - yarn start

notifications:
  email:
    recipients:
      - antonis162010@gmail.com
    on_success: always
    on_failure: always



