version: "3.3"

services:
  backapp:
    build: .
    image: ${CONTAINER_REGISTRY}:${CI_COMMIT_SHA}
    restart: always
    env_file:
      - .env${TYPE_ENV}
    environment: 
      - NODE_ENV
      - JWT_KEY
      - APP_PORT
      - APP_URL
      - MONGODB_URI
      - GC_EMAIL
      - GC_PROJECT_ID
      - GC_PUBSUB_TOPIC
      - GC_PRIVATE_KEY
    ports:
      - 3000:3000
