apiVersion: v1
kind: Service
metadata:
  name: ${FERRETERIA_UID}-cluster-ip-service
  labels:
    app: ${FERRETERIA_UID}-app
spec:
  type: NodePort
  selector:
    app: ${FERRETERIA_UID}-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${FERRETERIA_UID}-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${FERRETERIA_UID}-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ${FERRETERIA_UID}-app
    spec:
      containers:
        - name: ${FERRETERIA_UID}-app
          image: $DOCKER_USERNAME/backmean:$CI_COMMIT_SHA
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi